### ISSUE TITLE
The parse_darknet_yolo2.py 

### ISSUE THREAD

**Issue by xhzcyc** [ruiminshen/yolo-tf#4]
INFO:tensorflow:processing layer 20
INFO:tensorflow:yolo2_darknet/conv20/BatchNorm/beta: [1024]=1024
INFO:tensorflow:yolo2_darknet/conv20/BatchNorm/gamma: [1024]=1024
INFO:tensorflow:yolo2_darknet/conv20/BatchNorm/moving_mean: [1024]=1024
INFO:tensorflow:yolo2_darknet/conv20/BatchNorm/moving_variance: [1024]=1024
INFO:tensorflow:yolo2_darknet/conv20/weights: [3, 3, 3072, 1024]=28311552
Traceback (most recent call last):
  File "parse_darknet_yolo2.py", line 136, in <module>
    main()
  File "parse_darknet_yolo2.py", line 93, in main
    p = struct.unpack('%df' % cnt, f.read(4 * cnt))
struct.error: unpack requires a bytes object of length 113246208

**Comment by aruninnanje** [comment]
I get the same error, can you please share how you were able to solve this error?

**Comment by ilyoung-mindset** [comment]
@xhzcyc , @ruiminshen , @aruninnanje 
I also got the same error. can you please let me know any solutions?

**Comment by gengmujian10** [comment]
@ruiminshen @xhzcyc 
I got this error too, could you tell me how to solve this problem ?

**Comment by Liberus** [comment]
So. anyone solved this and can share a solution?
